# -*- coding: utf-8 -*-
"""LRModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PjB0zDV94AUPmtjo2pTejVXYG73M8jT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

df = pd.read_csv("marketing_campaign.csv", sep="\t")

df = df[
    [
        "Year_Birth",
        "Education",
        "Marital_Status",
        "Income",
        "Kidhome",
        "Teenhome",
        "MntWines",
        "MntMeatProducts",
        "MntFishProducts",
        "MntSweetProducts",
        "MntGoldProds",
        "NumDealsPurchases",
        "NumWebPurchases",
        "NumCatalogPurchases",
        "NumStorePurchases",
        "NumWebVisitsMonth",
        "Complain",
        "Response"
    ]
]


df = df.dropna()

df = df.drop_duplicates()

df["Age"] = 2026 - df["Year_Birth"]

df = df[df["Year_Birth"] > 1926]

df["Total_Spending"] = (
    df["MntWines"] +
    df["MntMeatProducts"] +
    df["MntFishProducts"] +
    df["MntSweetProducts"] +
    df["MntGoldProds"]
)

df["Total_Purchases"] = (
    df["NumWebPurchases"] +
    df["NumCatalogPurchases"] +
    df["NumStorePurchases"]
)

df["Children"] = df["Kidhome"] + df["Teenhome"]

plt.figure()
df["Response"].value_counts().plot(kind="bar")
plt.title("Campaign Response Graph")
plt.show()

plt.figure()
sns.boxplot(x="Response", y="Income", data=df)
plt.title("Income vs Response")
plt.show()

#plt.figure()
#sns.boxplot(x="Response", y="Total_Spending", data=df)
#plt.title("Spending vs Response")
#plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.select_dtypes(include=np.number).corr(), cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()


X = df[
    [
        "Education",
        "Marital_Status",
        "Income",
        "Age",
        "Kidhome",
        "Teenhome",
        "Total_Spending",
        "Total_Purchases",
        "NumDealsPurchases",
        "NumWebVisitsMonth",
        "Complain",
        "Children"
    ]
]

y = df["Response"]


X_trainval, X_test, y_trainval, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_trainval, y_trainval, test_size=0.25, random_state=42
)

#print("Train shape:", X_train.shape)
#print("Valid shape:", X_valid.shape)
#print("Test shape:", X_test.shape)


categorical_features = ["Education", "Marital_Status"]
numeric_features = [col for col in X.columns if col not in categorical_features]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", "passthrough", numeric_features)
    ]
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])


model.fit(X_train, y_train)

valid_pred = model.predict(X_valid)

print("\nVALIDATION SET PREDICTION RESULTS")
print(classification_report(y_valid, valid_pred))


test_pred = model.predict(X_test)

print("\nTEST SET PREDICTION RESULTS")
print(classification_report(y_test, test_pred))

cm = confusion_matrix(y_test, test_pred)
ConfusionMatrixDisplay(cm).plot()
plt.title("Confusion Matrix")
plt.show()

feature_names = model.named_steps["preprocessor"].get_feature_names_out()
coef = model.named_steps["classifier"].coef_[0]

importance = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coef
})

importance["Abs"] = importance["Coefficient"].abs()
importance = importance.sort_values("Abs", ascending=False)

print("\nTOP FEATURES")
print(importance.head(15))

plt.figure(figsize=(8,5))
top = importance.head(10)

plt.barh(top["Feature"], top["Coefficient"])
plt.title("Top Predictors of Campaign Response")
plt.gca().invert_yaxis()
plt.show()